# Generated by Django 4.2.1 on 2023-06-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('correo_electronico', models.CharField(max_length=50)),
                ('contrasena', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
    ]
